### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by gaorongchao** [RBVI/ChimeraX#15]
Is there anyway to use jupyter notebook instead of Jupyter QtConsole?
I use win10, first I add chimerax python to jupyter notebook kernel use :
`D:\software\ChimeraX` 1.3\bin\python.exe -m ipykernel install --user --name=ChimeraX`

Then I can create notebook use ChimeraX kernel.

```
from chimerax.core.session import *
from chimerax.core.commands import run

session = Session('a')
session
```
![1652856482(1)](https://user-images.githubusercontent.com/3361790/168975358-b63297e7-e6d2-45e2-a6f8-f175436cae96.png)

How to start a gui in jupyter notebook and use as Jupyter QtConsole?
Or crontal the opened gui in notebook?

**Comment by zjp** [comment]
We do not currently have plans to distribute the ChimeraX GUI outside of the ChimeraX distribution, and I'm not sure that what you want to do would be possible in a Jupyter notebook. If you were to call the function that initializes the GUI, it would never return control to the Jupyter notebook. The result would be that the rest of your cells would be blocked from running.

My current recommendation is to use `jupyter-qtconsole` through the `shell` command in ChimeraX. As a workaround for what you want to do, I would type work in the shell for a while, then type `%history`, and save the command record the console prints back to you as Python code. 

We are currently evaluating distributing ChimeraX modules as a library, which will allow you to import modules into your own Python environments and manipulate session files.

**Comment by gaorongchao** [comment]
It's not only save the command record, but the work flow, comment, notebook will much better than jupyter-qtconsole. 
Thank you for your reply!

**Comment by tomgoddard** [comment]
In the Jupyter notebooks I have used, the Jupyter notebook is the entire user interface.  Do you envision you would have the ChimeraX user interface showing and separately a Jupyter notebook window?  I don't think I ever see that because all the steps you would do through the user interface in ChimeraX would not be recorded in the notebook.

I guess you also envision directly typing ChimeraX commands into the notebook, not Python code.  You would have to have a lot of detailed knowledge to be able to directly call ChimeraX Python functions.  Currently the ChimeraX Log panel records all of your commands, and also most user interface buttons and menu also log equivalent commands.  And the Log panel can be saved using a right click on the panel to show the context menu entry Save As....  The command-line is at the bottom of the ChimeraX main window, you can't type commands directly into the Log, but if you could would that be what you are looking for?  When you save a session (*.cxs) file it remembers that entire log.  And it allows clicking on the commands in the Log to rerun them (use context menu entry "Executable links", otherwise the links take you to the documentation).

Thanks for you ideas about how to improve the ChimeraX user interface.
