### ISSUE TITLE
Question about PyQt6-Qt6

### ISSUE THREAD

**Issue by jerviedog** [RBVI/ChimeraX#23]
Hi, developers,

I tried to build ChimeraX from source, because the prebuilt ChimeraX didn't work on my Debian Stretch.

I have installed the required packages and Qt6.

An error occurred when the build process halted at building prereqs/PyQt. Specifically, when the build process tried to install PyQt6-Qt6.

The error was: 
ERROR: Could not find a version that satisfies the requirement PyQt6-Qt6==6.3.1 (from versions: none)
ERROR: No matching distribution found for PyQt6-Qt6==6.3.1

I looked up https://pypi.org/simple/pyqt6-qt6/, and found no such thing as PyQt6_Qt6-6.3.1-py3-**abi3**-manylinux_2_28_x86_64.whl, but only PyQt6_Qt6-6.3.1-py3-**none**-manylinux_2_28_x86_64.whl. 

I don't know about python building process, but I guess the **WHEEL_ABI** variable in the file prereqs/PyQt/Makefile.wheel.qt6 is the problem. 

Am I right? If so, how can I tell the build process to use the "none" version of PyQt6_Qt6?

Thanks very much.

**Comment by tomgoddard** [comment]
I doubt it is possible to use ChimeraX 1.4 which uses Qt 6.3 on such an old Linux distribution as Debian 9.  Instead I suggest you try ChimeraX 1.3 which uses the older Qt 5 and may be compatible.

Debian Stretch (ie Debian 9) is based on C library glibc 2.24 but the available PyQt6-Qt6 version 6.3.1 wheels requires glibc version 2.28 or newer as shown here

	https://pypi.org/project/PyQt6-Qt6/#files

The 2_28 in the .whl file name means glibc 2.28 or newer is required

	PyQt6_Qt6-6.3.1-py3-none-manylinux_2_28_x86_64.whl 

I would guess this means that PyQt 6 does not support old linux versions like Debian 9.  It is not clear whether Qt 6 supports the old Debian 9 as the have dropped support for most older Linux distributions.  The Qt 6 supported platform page

	https://doc.qt.io/qt-6/supported-platforms.html

says "Linux binary packages are linked against glibc 2.28".  While you could try to compile Qt 6 yourself that is a big job.  Although you say you have Qt 6, you also need the PyQt 6 package which I guess you would also need to compile.  And ChimeraX does not use your system versions so they would need to be integrated into the ChimeraX application.

Maybe it is possible to build Qt 6 and PyQt 6 for an older Linux but I bet it will be very difficult and the only practical solution is to use a more modern Linux distribution or an older ChimeraX version.

**Comment by gregcouch** [comment]
On https://doc.qt.io/qt-6/supported-platforms.html, the oldest supported Debian-based distribution is Ubuntu 20.04.  And that is based on Debian 11, a.k.a. Bullseye.  So the recommendation is to upgrade your base OS to something current and run legacy applications in a container, e.g., singularity/apptainer.

**Comment by jerviedog** [comment]
Dear tomgoddard,

You are right:) I should have tried older version. I switched to ChimeraX-13 and tried to compiled it myself.

After make install, the build process halted when it tried to curl the ambertools:

curl --silent --show-error --fail --insecure -O https://cxtoolshed.rbvi.ucsf.edu/prereqs/ambertools/ambertools-20-Linux-Debian-9.tar.bz2
curl: (22) The requested URL returned error: 404 Not Found

It seems that the file has been removed.

Can I just skip this tool? I think I don't need the simulation function.

Thanks.

**Comment by jerviedog** [comment]
Dear tomgoddard,

You are right:) I should have tried older version. I switched to ChimeraX-13 and tried to compiled it myself.

After make install, the build process halted when it tried to curl the ambertools:

curl --silent --show-error --fail --insecure -O https://cxtoolshed.rbvi.ucsf.edu/prereqs/ambertools/ambertools-20-Linux-Debian-9.tar.bz2
curl: (22) The requested URL returned error: 404 Not Found

It seems that the file has been removed.

Can I just skip this tool? I think I don't need the simulation function.

Thanks.

**Comment by tomgoddard** [comment]
I was suggesting just using the prebuilt ChimeraX 1.3 on the download page under Old Releases.  Why are you trying to compile ChimeraX?  ChimeraX depends on about 100 third-party libraries so it will probably be a lot of work for you to make sure all of those libraries are available on your Linux distribution.  The error you get is saying that the ambertools library binary that the ChimeraX build tries to install is not available on our servers.  Of the 100 libraries needed a dozen we had to build ourselves rather than get from a public repository, and those dozen are fetched from our server at  https://cxtoolshed.rbvi.ucsf.edu/prereqs/ <https://cxtoolshed.rbvi.ucsf.edu/prereqs/> and we only have those prebuilt libraries for the platforms we distribute on.  If you are trying to make some build on a new platform for example Debian 9 on ARM CPUs you would need to build all those libraries and I guess it would be weeks of effort.

So my advice is use our prebuilt ChimeraX.  Or if you are a ChimeraX developer then use a modern supported Linux.

**Comment by jerviedog** [comment]
Hi, tomgoddard,

Sorry for not mentioning that I have tried the prebuilt version first. 

The reason I tried to rebuild ChimeraX is that the prebuilt version depends (I guess) on libssl1.0.0. 

If I installed libssl1.0.2 instead, the installation failed because libssl1.0.0 is required. 

After I installed libssl1.0.0, the installation still failed because, I guess, the python ssl module uses libssl1.0.2. The error was: 

>     import _ssl             # if we can't import it, let the error propagate
> ImportError: /usr/lib/ucsf-chimerax/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so: symbol SSL_CTX_set_alpn_protos, version OPENSSL_1.0.2 not defined in file libssl.so.1.0.0 with link time reference

Do you have a suggestion? But if it is too difficult to use ChimeraX on Debian 9, I could still use Chimera:)

Thanks very much.

**Comment by tomgoddard** [comment]
Wrong libssl version is a common problem on Linux.  Our Linux expert Greg Couch may be able to help.

	Tom

**Comment by tomgoddard** [comment]
A couple of things.  (1) Use the .deb or .rpm packages if you can -- 
they include dependencies that the package manager will install if they 
are missing.  (2) If ChimeraX needs libssl1.0.0 and you have 
libssl1.0.2, then normally I would suggest making a symbolic link for it 
in the CHIMERAX/lib directory that points to libssl1.0.2 (where CHIMERAX 
is the directory that you have installed it in.  But in your case, it 
appears that you need to replace 
/usr/lib/ucsf-chimerax/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so. 
If you have Python 3.9 installed on your system, or if you compile 
Python3.9 on your system,  you could replace ChimeraX's 
_ssl.cpython-39-x86_64-linux-gnu.so with that version.

You should be aware that the Qt Company does not support Qt 6 on Debian 
9.  So you will need to compile Qt 6 as well.  You will need to replace 
the PyQt6-Qt6 and PyQt6-WebEngine-Qt6 wheels from pypi that won't 
install on Debian 9.

I strongly recommend that instead of trying to get ChimeraX to run on an 
old system, that you upgrade your system.  If you have legacy 
applications that you need to run, then they should be put in a 
singularity/apptainer container.  Once they are in a container, they 
will continue to run on newer systems.

     Good luck,

     Greg
