### ISSUE TITLE
Webpage not found

### ISSUE THREAD

**Issue by Pommert** [RBVI/ChimeraX#34]
Dear RBVI-Team,

if i try to go to the download page of ChimeraX i'm getting a "The requested URL was not found on this server." error (the entire ChimeraX branch seems to be missing, because the older version is still online).

Best regards
Max

**Comment by tomgoddard** [comment]
We know.  Our servers are down unexpectedly and it is being worked on.  Thanks.

**Comment by Pommert** [comment]
fingers crossed that you get it fixed quickly

**Comment by tomgoddard** [comment]
Hopefully back up today.  The web site data was hosted on a UCSF 10,000 node compute cluster file system that has been down for 10 days.  We brought up the ChimeraX web site a few days ago even though the maintenance of the disk array has not yet been finished (expected tomorrow), and that burned us because unexpectedly web site files disappeared this morning.

**Comment by tomgoddard** [comment]
ChimeraX web site is back up.  But I would not be surprised if it goes down again.  I expect it to become stable once the UCSF Wynton cluster comes back online.
