### ISSUE TITLE
Predicting a large structure with ChimeraX using alphafold: high variability in protein structure

### ISSUE THREAD

**Issue by dorkylever** [RBVI/ChimeraX#42]
Hi All, 

I'm using the latest daily build (March 20th 2024) and I'm following the instructions in [the tutorial for predicting large structures](https://www.youtube.com/watch?v=H-pDs9rZtkw). I ultimately want to see if Alphafold can determine the resulting protein structure of a handful of missense mutations. 

The process works pretty well for proteins < 500 residues but structures > 1000 residues have highly variable protein structures.  For example, my predicted structure of murine C2cd3 (with the same protein sequence) is vastly different from the reviewed structure. 

The screenshots are after protein alignment with Matchmaker (aligning using only residues with a bfactor > 80). 

Reviewed Structure ([A2AUM9](https://alphafold.ebi.ac.uk/entry/A2AUM9)):
![image](https://github.com/RBVI/ChimeraX/assets/41981766/9fb99e5c-526f-4f64-921c-d4aee5e29b66)

Predicted Structure:
![image](https://github.com/RBVI/ChimeraX/assets/41981766/31e0102d-fc54-4f77-9cc5-d29a7ea58dd4)

Do you have any parameters that can be passed to alphafold to reduce this variability, or,  is it just a problem with predicting large structures???

Kind Regards, 
Kyle

**Comment by tomgoddard** [comment]
This is a question about AlphaFold, not about ChimeraX.  AlphaFold often gives wrong predictions on large proteins and in general there are no parameters that fix that problem.  But Alphafold gives pretty good error estimates in its predicted aligned error (PAE) that tell you whether it thinks it is folded correctly.  The correctness of the domain packing is often not apparent from the pLDDT coloring of the model.  I suggest you look at this video on how to view PAE error estimates in ChimeraX

    https://www.youtube.com/watch?v=oxblwn0_PMM

I don't understand what you mean by "reviewed structure".  You link to the AlphaFold database model [A2AUM9](https://alphafold.ebi.ac.uk/entry/A2AUM9).  If your prediction does not match that Alphafold database prediction it could be for a variety of reasons.  The AlphaFold software has been updated several times since the database was made and now gives different results.  And the ChimeraX AlphaFold uses a web based implementation (ColabFold) that uses reduced databases and no structure templates which may also result if different structures.
