### ISSUE TITLE
Fedora 41: Flatpack doesnt show settings or tool shed window

### ISSUE THREAD

**Issue by aretaon** [RBVI/ChimeraX#48]
# Description of the issue

I installed ChimeraX 1.8 on Fedora 41 using flatpak (see log below). The application starts and looks okay, however, I cannot open new windows (e.g. when clicking on Favorites -> Settings or on Tools -> More Tools, nothing happens). The same is true for the rpm-Version.
Potential suspect might be my graphics card which is an AMD Radeon™ RX 640 with open source kernel drivers and the windowing system is Wayland.

# Logs
## Installation
> sudo flatpak install
>  ChimeraX-1.8.flatpak 
> 
> edu.ucsf.rbvi.ChimeraX permissions:
>     ipc      network             wayland     x11
>     dri      file access [1]
> 
>     [1] home, host, xdg-cache/ChimeraX:create, xdg-config/ChimeraX:create,
>         xdg-data/ChimeraX:create, xdg-desktop, xdg-download/ChimeraX:create
> 
> 
>         ID                               Branch           Op           Remote                   Download
>  1. [✓] edu.ucsf.rbvi.ChimeraX           master           i            chimerax-origin          0 bytes
> 
> Installing…
> Note that '/var/lib/flatpak/exports/share' is not in the search path
> set by the XDG_DATA_HOME and XDG_DATA_DIRS
> environment variables, so applications may not
> be able to find it until you set them. The
> directories currently searched are:
> 
> - /root/.local/share
>         ID                               Branch           Op           Remote                   Download
>  1. [✓] edu.ucsf.rbvi.ChimeraX           master           i            chimerax-origin          0 bytes
> 
> Installation complete.

## Application start

```
flatpak run edu.ucsf.rbvi.ChimeraX 
Gtk-Message: 13:24:45.383: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:24:45.383: Failed to load module "pk-gtk-module"
Gtk-Message: 13:24:45.384: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:24:45.384: Failed to load module "pk-gtk-module"
NOTE: available bundle cache has not been initialized yet

```

**Comment by gregcouch** [comment]
I'll spin up a Fedora 41 virtual machine and check.  If I had to guess from your description, the problem is most likely ChimeraX's use of Wayland (via the Qt UI libraries).  And the solution might be ChimeraX 1.10 :-(.  The open source AMD drivers are generally excellent.  Switching from Wayland to X11, depends on what display manager you're using -- for gdm, edit /etc/gdm3/custom.conf and add "WaylandEnable=false".

**Comment by gregcouch** [comment]
The ChimeraX 1.8 flatpak works using Wayland in a Fedora 41 virtual machine.  The VM was initially using Mesa 24.2.4.  After updating, to Mesa 24.2.7, it still works.

So maybe it is the graphics driver.  Make sure your system is fully patched.  If there is a proprietary driver from AMD, you could try that instead of the open source Mesa driver.

I tried not using Wayland by editing /etc/gdm/custom.conf, and that didn't work.  I had to stop and disable the gdm service.  Then install lightdm, and enable and start it.

**Comment by aretaon** [comment]
Thanks for looking into that! I was running on Mesa 24.2.7 all along, however, the reason turned out to be not software-related at all. I had a faulty DP-cable which seems to have caused troubles on the GPU itself. After removing the cable and re-plugging the PCIe connector everything runs as supposed now. No clue how the error translates into the observed problem. And sorry to have suspected ChimeraX in the first place ;)
